{
  pkgs,
  inputs,
  importsFromAttrs,
  ...
}:
{
  imports = importsFromAttrs {
    importByDefault = true;
    modules = inputs.self.moduleTree.nixos;
    imports = {
      configurations = false;
      #profiles.nix = false;
      #profiles.aliases = false;
    };
  };

  # There are some examples with host-specific configurations

  # GPU acceleration
  #hardware.opengl.extraPackages = with pkgs; [ intel-media-driver ];

  # RAM-specific
  #boot.tmp.useTmpfs = true;
  #zramSwap.memoryPercent = 50;

  # other host-specific settings
  #services.tlp.settings = {
  #  START_CHARGE_THRESH_BAT0 = 40;
  #  STOP_CHARGE_THRESH_BAT0 = 50;
  #};

  # Be sure to read the comments about this option in the configuration
  # generated by the `nixos-generate-config` command
  #system.stateVersion = "24.05";
}
